spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/testdb?characterEncoding=utf-8&useSSL=false
mybatis:
#  config-location: classpath:mybatis-config.xml
  #mapper-locations: classpath:xml/*.xml
  type-aliases-package: com.bj58.mybatisgeneration.entity
  mapper-locations: com.bj58.mybatisgeneration.dao.*

